import uproot
import pandas as pd 
import numpy as np 
import h5py
import math
from unc_funcs import *

# DATAFRAME FILES:

gray_df_dir = "/exp/icarus/data/users/gputnam/thesis-work/DMCP2023G/mc-F/"
detVar_labels = [
    "Middle Ind. Opaque",
    "Middle Ind. Transparent",
    "Front Ind. Gain Low",
    "Front Ind. Gain High",
    "Noise 1.2x", 
    "Space Charge 2x",
    "Ind0 Nom" # ??
]

# Higgs Files
# Note: Gray made these. They exclude final state pions.
higgs_files = [
    gray_df_dir + "F2-Higgs_M220_nom_evt.df",
    gray_df_dir + "F2-Higgs_M240_nom_evt.df",
    gray_df_dir + "F2-Higgs_M260_nom_evt.df",
    gray_df_dir + "F2-Higgs_M280_nom_evt.df",
    gray_df_dir + "F2-Higgs_M300_nom_evt.df",
    gray_df_dir + "F2-Higgs_M340_nom_evt.df"
]
higgs_220_detVar_files = [
    gray_df_dir + "F2-Higgs_M220_ind1bin0_evt.df", # "Middle Ind. Opaque"
    gray_df_dir + "F2-Higgs_M220_ind1bin14_evt.df", # "Middle Ind. Transparent"
    gray_df_dir + "F2-Higgs_M220_ind0glo_evt.df", # "Front Ind. Gain Low"
    gray_df_dir + "F2-Higgs_M220_ind0ghi_evt.df", # "Front Ind. Gain High"
    gray_df_dir + "F2-Higgs_M220_noiselhi_evt.df", # "Noise 1.2x"
    gray_df_dir + "F2-Higgs_M220_sce2x_evt.df", # "Space Charge 2x"
    gray_df_dir + "F2-Higgs_M220_ind0nom_evt.df" # "Ind 0 Nom"
]
higgs_240_detVar_files = [
    gray_df_dir + "F2-Higgs_M240_ind1bin0_evt.df", # "Middle Ind. Opaque"
    gray_df_dir + "F2-Higgs_M240_ind1bin14_evt.df", # "Middle Ind. Transparent"
    gray_df_dir + "F2-Higgs_M240_ind0glo_evt.df", # "Front Ind. Gain Low"
    gray_df_dir + "F2-Higgs_M240_ind0ghi_evt.df", # "Front Ind. Gain High"
    gray_df_dir + "F2-Higgs_M240_noiselhi_evt.df", # "Noise 1.2x"
    gray_df_dir + "F2-Higgs_M240_sce2x_evt.df", # "Space Charge 2x"
    gray_df_dir + "F2-Higgs_M240_ind0nom_evt.df" # "Ind 0 Nom"
]
higgs_260_detVar_files = [
    gray_df_dir + "F2-Higgs_M260_ind1bin0_evt.df", # "Middle Ind. Opaque"
    gray_df_dir + "F2-Higgs_M260_ind1bin14_evt.df", # "Middle Ind. Transparent"
    gray_df_dir + "F2-Higgs_M260_ind0glo_evt.df", # "Front Ind. Gain Low"
    gray_df_dir + "F2-Higgs_M260_ind0ghi_evt.df", # "Front Ind. Gain High"
    gray_df_dir + "F2-Higgs_M260_noiselhi_evt.df", # "Noise 1.2x"
    gray_df_dir + "F2-Higgs_M260_sce2x_evt.df", # "Space Charge 2x"
    gray_df_dir + "F2-Higgs_M260_ind0nom_evt.df" # "Ind 0 Nom"
]
higgs_280_detVar_files = [
    gray_df_dir + "F2-Higgs_M280_ind1bin0_evt.df", # "Middle Ind. Opaque"
    gray_df_dir + "F2-Higgs_M280_ind1bin14_evt.df", # "Middle Ind. Transparent"
    gray_df_dir + "F2-Higgs_M280_ind0glo_evt.df", # "Front Ind. Gain Low"
    gray_df_dir + "F2-Higgs_M280_ind0ghi_evt.df", # "Front Ind. Gain High"
    gray_df_dir + "F2-Higgs_M280_noiselhi_evt.df", # "Noise 1.2x"
    gray_df_dir + "F2-Higgs_M280_sce2x_evt.df", # "Space Charge 2x"
    gray_df_dir + "F2-Higgs_M280_ind0nom_evt.df" # "Ind 0 Nom"
]
higgs_300_detVar_files = [
    gray_df_dir + "F2-Higgs_M300_ind1bin0_evt.df", # "Middle Ind. Opaque"
    gray_df_dir + "F2-Higgs_M300_ind1bin14_evt.df", # "Middle Ind. Transparent"
    gray_df_dir + "F2-Higgs_M300_ind0glo_evt.df", # "Front Ind. Gain Low"
    gray_df_dir + "F2-Higgs_M300_ind0ghi_evt.df", # "Front Ind. Gain High"
    gray_df_dir + "F2-Higgs_M300_noiselhi_evt.df", # "Noise 1.2x"
    gray_df_dir + "F2-Higgs_M300_sce2x_evt.df", # "Space Charge 2x"
    gray_df_dir + "F2-Higgs_M300_ind0nom_evt.df" # "Ind 0 Nom"
]
higgs_340_detVar_files = [
    gray_df_dir + "F2-Higgs_M340_ind1bin0_evt.df", # "Middle Ind. Opaque"
    gray_df_dir + "F2-Higgs_M340_ind1bin14_evt.df", # "Middle Ind. Transparent"
    gray_df_dir + "F2-Higgs_M340_ind0glo_evt.df", # "Front Ind. Gain Low"
    gray_df_dir + "F2-Higgs_M340_ind0ghi_evt.df", # "Front Ind. Gain High"
    gray_df_dir + "F2-Higgs_M340_noiselhi_evt.df", # "Noise 1.2x"
    gray_df_dir + "F2-Higgs_M340_sce2x_evt.df", # "Space Charge 2x"
    gray_df_dir + "F2-Higgs_M340_ind0nom_evt.df" # "Ind 0 Nom"
]

# ALP Files (ALPs WITHOUT MASS SUPPRESSION)

alp_nosup_files = [
    #"/icarus/data/users/jdyer/dimuon-data/axion-no-suppression/alp_M500_faE6_DMC2023G_evt.df" # regenerated with fa=E6, by me.
    #"/exp/icarus/data/users/jdyer/DMCP2023G/axions/alp_M300_faE6_evt.df",
    "/exp/icarus/data/users/jdyer/DMCP2023G/axions/alp_M300_faE5_evt.df",
    "/exp/icarus/data/users/jdyer/DMCP2023G/axions/alp_M500_faE6_evt.df",
    #"/exp/icarus/data/users/jdyer/DMCP2023G/axions/alp_M500_faE5_evt.df"
    "/exp/icarus/data/users/jdyer/DMCP2023G/axions/2408/alp_M300_faE6_evt.df" #regenerated by Gray Aug.'24.
]

# Nu Files

nu_file = gray_df_dir + "F-MCNuPhase2_evt.df"
cohlike_nu_file = gray_df_dir + "F-CohLike_nom_evt.df"

# note: This sample contains coh-LIKE events. Really, it is any event with a muon or a pion in the final state. This means that the interaction isn't necessarily a coherent interaction, but it just looks like one.

# note: It is possible that there is pileup in the neutrino interactions. If it happens that two neutrino interactions overlap in a single reconstructed slice, then even if the "bonus" one is not coh-like, it would be included in this sample as well. Having two neutrino interactions overlap like this is extremely unlikely, so this probably never happens.

# note: We only have detector variation samples for coherent-like events. 
cohlike_nu_detVar_files = [
    gray_df_dir + "F-CohLike_ind1bin0_evt.df", # "Middle Ind. Opaque"
    gray_df_dir + "F-CohLike_ind1bin14_evt.df", # "Middle Ind. Transparent"
    gray_df_dir + "F-CohLike_ind0glo_evt.df", # "Front Ind. Gain Low"
    gray_df_dir + "F-CohLike_ind0ghi_evt.df", # "Front Ind. Gain High"
    gray_df_dir + "F-CohLike_noiselhi_evt.df", # "Noise 1.2x"
    gray_df_dir + "F-CohLike_sce2x_evt.df", # "Space Charge 2x"
    gray_df_dir + "F-CohLike_ind0nom_evt.df" # "Ind 0 Nom"
    # MISSING: CALHI, CALLO # MAY 3, 2024 # May 5: Nevermind! Gray made that spectrum for events in their signal box.
    ]

# Data Files

onbeamfile_Run1 = gray_df_dir + "F-Run1-OnBeam_evt.df"
onbeamfile_Run2 = gray_df_dir + "F4-Run2-OnBeam_evt.df"

offbeamfile_Run1 = gray_df_dir + "F-Run1-OffBeam_evt.df"
offbeamfile_Run2 = gray_df_dir + "F2-Run2-OffBeam_evt.df"

# Notes:
# There is overlap between files that are used in different notebooks, but the data can be used differently. E.g.:
# For MC Event Selection and MC Studies, event data frames are extracted w/ Pandas function:
#    pd.read_hdf(filename, key='evt') 
# For Data/MC Comparisons nb, event data frames are extracted with custom function: 
#    data.mc_dataset(mccohfile, "evt", mcnukey="mcnuweight").df
# This function takes a while, becuase it uses information in [] to compute weights needed to run systematics, and then inserts that into the returned dataframe. 

